### ISSUE TITLE
Where can I get the dataset?

### ISSUE THREAD

**Issue by LeiyanGithub** [qhjqhj00/acl2024_cfic#1]

**Comment by qhjqhj00** [comment]
Please see https://huggingface.co/datasets/TommyChien/ACL24_CFIC

**Comment by LeiyanGithub** [comment]
<img width="698" alt="image" src="https://github.com/user-attachments/assets/0793e2f4-e78d-43a6-9f73-0b77e064d2df">

Hi, Is the dataset available for use?
